version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: servercomm
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  server-comm:
    image: aoikazto/aswcloud-server
    restart: always
    ports:  
      - 8080:8088
    environment:
      - MONGODB_SERVER: localhost
      - MONGODB_PORT: 27017
      - MONGODB_DATABASE: servercomm
      - JWT_SECRET_TOKEN: jwt_secret_token_9397c1c9fbde5a790aa42c876fb451b1116b8247bed0f2abaf7de7a93b6c2ef07cc0b87281ae5138efe34c48004113c16edd82d1a12f08714e32d34801c10089d916190284bd4f4a90441ed6f5a18e7e0a1420b120b243a7b9ff646deb8a855e
